#!/bin/bash
echo "## Build docker core"
docker build -t somenergia/plataforma-core -f ".dockers/plataforma-core/Dockerfile" .
#echo "## Build docker"
#docker build -t somenergia/plataforma -f ".dockers/plataforma/Dockerfile" .
echo "## Build devel docker"
docker build -t somenergia/plataforma-devel -f ".dockers/plataforma-devel/Dockerfile" .
