FROM mysql:5.7
MAINTAINER  Som Energia

ENV MYSQL_ROOT_PASSWORD "toor"
ENV MYSQL_USER "plataforma"
ENV MYSQL_PASSWORD "plataforma"
ENV MYSQL_DATABASE "plataforma"

# Add initial database
#COPY .docker/mysql/base.sql  /docker-entrypoint-initdb.d/base.sql

