#!/bin/bash
APPPATH=$(realpath "./")
#APPDATA="$APPPATH/docker/elggdata"
#APPDATABASE="$APPPATH/docker/elggdatabase"
DOCKERIMAGE="somenergia/plataforma"

echo "## Run $DOCKERIMAGE image"
echo "## Cuentas accesso docker ##"
echo "## Plataforma: admin Passwd: adminadmin ##"
echo "## Admin Base datos: admin Passwd: plataforma ##"


#docker run -it -p 8000:80 -p 3306:3306 -v "${APPPATH}":/app:z -v "${APPDATA}":/data:z -v "${APPDATABASE}":/var/lib/mysql:z "$DOCKERIMAGE"
docker run -it -p 8000:80 -p 3306:3306 -v "${APPPATH}":/app:z "$DOCKERIMAGE"
